ci: :sparkles: Add CI in Aws of API create Availability

diff --git a/.github/workflows/DeployCreateAvailabilityQA.yml b/.github/workflows/DeployCreateAvailabilityQA.yml
--- a/.github/workflows/DeployCreateAvailabilityQA.yml
+++ b/.github/workflows/DeployCreateAvailabilityQA.yml
@@ -1,4 +1,4 @@
-name: Build and Push Docker Images in Create-Availability
+name: Build, Push, and Deploy Create-Availability
 
 on:
   push:
@@ -22,8 +22,47 @@ jobs:
 
     - name: Build and Push Docker Image
       run: |
-        # Construir la imagen Docker
         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/create-availability:latest ./AVAILABILITY-MANAGEMENT/Create-Availabilty/
-
-        # Push de la imagen a Docker Hub
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/create-availability:latest
+
+  deploy-aws:
+    needs: build-and-push
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Set permissions for private key
+      run: |
+        echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
+        chmod 600 key.pem
+
+    - name: Update system and install Docker if not present
+      run: |
+        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST }} << 'EOF'
+        # Update the system
+        sudo yum update -y
+
+        # Check if Docker is installed
+        if ! command -v docker &> /dev/null
+        then
+          echo "Docker not found, installing..."
+          sudo yum install -y docker
+          sudo systemctl start docker
+          sudo systemctl enable docker
+        else
+          echo "Docker is already installed."
+        fi
+
+        # Ensure Docker is running
+        sudo systemctl start docker
+        sudo systemctl enable docker
+        EOF
+
+    - name: Deploy Docker Container
+      run: |
+        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST }} << 'EOF'
+        sudo docker stop create-availability-container || true
+        sudo docker rm create-availability-container || true
+        sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/create-availability:latest
+        sudo docker run -d -p 3007:3007 --name create-availability-container ${{ secrets.DOCKERHUB_USERNAME }}/create-availability:latest
+        sudo docker image prune -f
+        EOF
